import { addDays, addMonths, setHours, setMinutes } from "date-fns";
import type { BrainSnapshot, Project, Task } from "./types";

export function createDemoSnapshot(now = new Date()): BrainSnapshot {
  const workProject: Project = {
    id: "project-retail-architecture-memo",
    areaId: "work",
    title: "Prepare retail architecture memo",
    outcome: "A concise architecture memo is ready for leadership review.",
    status: "active",
    reviewAt: addDays(now, 7),
    createdAt: now,
    updatedAt: now,
    completedAt: null
  };

  const dentistAt = setMinutes(setHours(addDays(now, 3), 10), 30);

  const tasks: Task[] = [
    {
      id: "task-draft-memo-outline",
      areaId: "work",
      projectId: workProject.id,
      title: "Draft outline for memo",
      notes: "Keep this to the argument structure and open questions.",
      status: "next",
      kind: "task",
      dueAt: null,
      deferUntil: null,
      reviewAt: null,
      recurrenceRule: null,
      focus: false,
      energy: "medium",
      estimateMinutes: 45,
      waitingOn: null,
      triggerCue: null,
      triggerAction: null,
      source: "demo",
      createdAt: now,
      updatedAt: now,
      completedAt: null
    },
    {
      id: "task-finance-metrics",
      areaId: "work",
      projectId: workProject.id,
      title: "Need metrics from finance partner",
      notes: "Follow up before the memo review window closes.",
      status: "waiting",
      kind: "task",
      dueAt: null,
      deferUntil: null,
      reviewAt: now,
      recurrenceRule: null,
      focus: false,
      energy: null,
      estimateMinutes: 10,
      waitingOn: "Finance partner",
      triggerCue: null,
      triggerAction: null,
      source: "demo",
      createdAt: now,
      updatedAt: now,
      completedAt: null
    },
    {
      id: "task-buy-air-filters",
      areaId: "personal",
      projectId: null,
      title: "Buy air filters",
      notes: "Check furnace size before ordering.",
      status: "next",
      kind: "task",
      dueAt: null,
      deferUntil: null,
      reviewAt: null,
      recurrenceRule: null,
      focus: false,
      energy: "low",
      estimateMinutes: 15,
      waitingOn: null,
      triggerCue: null,
      triggerAction: null,
      source: "demo",
      createdAt: now,
      updatedAt: now,
      completedAt: null
    },
    {
      id: "task-woodworking-bench",
      areaId: "personal",
      projectId: null,
      title: "Build woodworking bench",
      notes: "Important someday idea. Do not let it crowd active work.",
      status: "incubator",
      kind: "reference",
      dueAt: null,
      deferUntil: null,
      reviewAt: addMonths(now, 1),
      recurrenceRule: null,
      focus: false,
      energy: null,
      estimateMinutes: null,
      waitingOn: null,
      triggerCue: null,
      triggerAction: null,
      source: "demo",
      createdAt: now,
      updatedAt: now,
      completedAt: null
    },
    {
      id: "task-dev-tooling-cleanup",
      areaId: "work",
      projectId: null,
      title: "Explore internal dev tooling cleanup",
      notes: "Ready for monthly incubator review.",
      status: "incubator",
      kind: "reference",
      dueAt: null,
      deferUntil: null,
      reviewAt: now,
      recurrenceRule: null,
      focus: false,
      energy: null,
      estimateMinutes: null,
      waitingOn: null,
      triggerCue: null,
      triggerAction: null,
      source: "demo",
      createdAt: now,
      updatedAt: now,
      completedAt: null
    },
    {
      id: "task-dentist-follow-up",
      areaId: "personal",
      projectId: null,
      title: "Dentist appointment follow-up",
      notes: "Scheduled because this is a real time-bound commitment.",
      status: "scheduled",
      kind: "reminder",
      dueAt: dentistAt,
      deferUntil: null,
      reviewAt: null,
      recurrenceRule: null,
      focus: false,
      energy: null,
      estimateMinutes: 10,
      waitingOn: null,
      triggerCue: null,
      triggerAction: null,
      source: "demo",
      createdAt: now,
      updatedAt: now,
      completedAt: null
    },
    {
      id: "task-standup-recap",
      areaId: "work",
      projectId: null,
      title: "Send recap to team",
      notes: "",
      status: "inbox",
      kind: "reminder",
      dueAt: null,
      deferUntil: null,
      reviewAt: null,
      recurrenceRule: null,
      focus: false,
      energy: null,
      estimateMinutes: 5,
      waitingOn: null,
      triggerCue: "standup ends",
      triggerAction: "send recap to team",
      source: "demo",
      createdAt: now,
      updatedAt: now,
      completedAt: null
    }
  ];

  return {
    areas: [
      { id: "work", name: "Work", archived: false },
      { id: "personal", name: "Personal", archived: false }
    ],
    projects: [workProject],
    tasks
  };
}
